# Generated by Django 3.2.12 on 2022-03-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_customer_hobby_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby_factor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorname', models.CharField(max_length=20)),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_name_tb')),
            ],
        ),
    ]
