# Generated by Django 3.2.12 on 2022-04-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_hobby_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimunage', models.IntegerField()),
                ('maximumage', models.IntegerField()),
                ('factorname', models.CharField(max_length=20)),
            ],
        ),
    ]
