# Generated by Django 3.2.12 on 2022-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0008_agefactor_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agefactor_tb',
            name='minimunage',
        ),
        migrations.AddField(
            model_name='agefactor_tb',
            name='minimumage',
            field=models.IntegerField(default=2),
        ),
    ]
