# Generated by Django 3.2.12 on 2022-04-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_admin', '0012_seasoncountry_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('filter_status', models.CharField(max_length=20)),
                ('recieverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievername', to='site_admin.register_tb')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendername', to='site_admin.register_tb')),
            ],
        ),
    ]
