# Generated by Django 3.2.12 on 2022-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_tb',
            name='filter_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
