# Generated by Django 3.2.12 on 2022-04-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_seasoncountry_tb'),
        ('site_user', '0002_auto_20220402_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.message_tb')),
                ('recieverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.register_tb')),
            ],
        ),
    ]
