# Generated by Django 3.2.12 on 2022-04-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_seasoncountry_tb'),
        ('site_user', '0003_trash_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20)),
                ('contactid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactid', to='site_admin.register_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='site_admin.register_tb')),
            ],
        ),
    ]
