# Generated by Django 3.2.12 on 2022-04-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_seasoncountry_tb'),
        ('site_user', '0007_alter_customisehobbyfactor_hobbyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='customisehobbyfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_factor_tb')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.customer_hobby_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.register_tb')),
            ],
        ),
    ]
