# Generated by Django 3.2.12 on 2022-04-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_seasoncountry_tb'),
        ('site_user', '0008_customisehobbyfactor_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisehobbyfactor_tb',
            name='hobbyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_name_tb'),
        ),
    ]
