# Generated by Django 3.2.12 on 2022-04-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0009_alter_customisehobbyfactor_tb_hobbyid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customisehobbyfactor',
        ),
    ]
