# Generated by Django 3.2.12 on 2022-04-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0016_alter_customiseseasoncountry_tb_factorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customiseseasoncountry_tb',
        ),
    ]
